### ISSUE TITLE
100% cpu usage in macbook air

### ISSUE THREAD

**Issue by xiamx** [scoutapp/scout_realtime#41] opened 2014-03-27 16:21 UTC
the title says it. I'm using Version 33.0.1750.152

**Comment by itsderek23** [comment] 2014-03-27 16:22
Sorry - mind sharing the following:
- Your operating system and version
- CPU specs

**Comment by xiamx** [comment] 2014-03-27 16:25
Running on OSX 10.9
  Model Name:   MacBook Air
  Model Identifier: MacBookAir5,2
  Processor Name:   Intel Core i7
  Processor Speed:  2 GHz
  Number of Processors: 1
  Total Number of Cores:    2
  L2 Cache (per Core):  256 KB
  L3 Cache: 4 MB

**Comment by xiamx** [comment] 2014-03-27 16:40
I tested in firefox, also 100% cpu usage. So i'm changing the title of this issue

**Comment by itsderek23** [comment] 2014-04-28 18:54
Spent some time looking into performance on the Javascript-side. 

The vast majority of time is spent on the animation transitions. When removed, the CPU usage cuts down by more than half.

The problem is that this makes the UI very jarring as the charts are shifted over every second.

Here's a screenshot of the current scout_realtime cpu profile w/animations:

![scout realtime cpu profile](https://cloud.githubusercontent.com/assets/7880/2821371/4adfc830-cf05-11e3-9df2-0b21168a2479.jpg)

Here's a screen w/o animations and using setInterval to handle the refresh:

![scout realtime w_o animation](https://cloud.githubusercontent.com/assets/7880/2821407/c8d55890-cf05-11e3-8430-a435165addd8.jpg)

There are a max of 34 charts displayed (4 overview + 10*3 process), this means:
- 34 timers for path transitions
- 4 timers for x-axis transitions

At present, I'm not aware of a workaround to make this less cpu-heavy, so I'll be marking this as "won't fix". If a solution comes up, we're more than happy to merge it in.

**Closed as completed by itsderek23** 2014-04-28 18:54 UTC
