### ISSUE TITLE
Relative path issue on reverse Proxy

### ISSUE THREAD

**Issue by ankitguptag18** [scoutapp/scout_realtime#27] opened 2014-03-12 14:26 UTC
Hi,

I have multiple servers so I would like to consolidate all the servers top via a single monitor page. So I was doing a reverse proxy to each server say www.example.com/server1/top www.example.com/server2/top etc. The problem that I faced was that some of the static file paths were relative paths and not mentioned correctly, few of them were relative to the path and some were relative to domain.

The graphs were not generating this way as the scripts files were not getting loaded. I started getting data when I changed these relative path from domain based to path based. I Hope you will consider these changes in your next release.

**Comment by andre** [comment] 2014-03-12 17:29
I think this is the same root cause as https://github.com/scoutapp/scout_realtime/issues/18?

**Comment by ankitguptag18** [comment] 2014-03-13 13:54
Changes I made for it to work was to change src="/......" to src="......." under img node, script node etc:
Hoping to see these changes in the coming updates.

There are other files as well which will need these changes. I stopped making changes once the graph started to plot.

lib/ruby/gems/1.9.1/gems/scout_realtime-1.0.1/lib/scout_realtime/web/views

index.rb 
Original Last Line
script src="/javascripts/application.js"

Changed
script src="javascripts/application.js"

Layout.erb
Original
script src="/javascripts/d3.v3.min.js"
script src="/javascripts/jquery.debouncedresize.js"
script src="/javascripts/d3.linechart.js"

Changed
script src="javascripts/d3.v3.min.js"
script src="javascripts/jquery.debouncedresize.js"
script src="javascripts/d3.linechart.js"

Slidebar_bottom.erb
Original
img src="/images/github.png"
img src="/images/scout.png"

Changed
img src="images/github.png"
img src="images/scout.png"

lib/ruby/gems/1.9.1/gems/scout_realtime-1.0.1/lib/scout_realtime/web/javascripts

application.js

Original
$.getJSON("/stats.json", function (d) {

Changed
$.getJSON("stats.json", function (d) {

**Comment by andre** [comment] 2014-03-14 04:17
See https://github.com/scoutapp/scout_realtime/issues/18#issuecomment-37615463

**Comment by itsderek23** [comment] 2014-03-14 20:06
scout_realtime -v1.0.3 has been released with this update.

**Closed as completed by itsderek23** 2014-03-14 20:06 UTC
